### ISSUE TITLE
构建区块链时出错，baas-fabricengine打印 Could not find profile:  OrdererGenesis. 求助~~~

### ISSUE THREAD

**Issue by LeoNumber1** [jonluo94/baasmanager#2]
![image](https://user-images.githubusercontent.com/12524129/61526388-e94ec200-aa4c-11e9-99a6-d0dfc68095d2.png)
点击构建时，baas-fabricengine打印出错误
![image](https://user-images.githubusercontent.com/12524129/61526489-1307e900-aa4d-11e9-9710-32a3bb19f1a9.png)
自己DEBUG了一会儿，发现c.profile, c.configPath都有值，configtx.yaml也正常生成，下面是configtx.yaml文件的一部分：
Profiles:
  OrdererGenesis:
    Policies:
      Readers:
        Type: ImplicitMeta
        Rule: ANY Readers
      Writers:
        Type: ImplicitMeta
        Rule: ANY Writers
      Admins:
        Type: ImplicitMeta
        Rule: MAJORITY Admins
    Capabilities:
      V1_3: true
    Orderer:
      OrdererType: solo
      Addresses:
        - orderer0.adminblcokkcccchainorderer:7050
      BatchTimeout: 2s

请问到底是哪里的错误，求助~~~~~~

**Comment by Alilice** [comment]
同问~

**Comment by jonluo94** [comment]
viper版本导致字母大小写的问题,已解决
