### ISSUE TITLE
创建channel失败，失败原因：[ERRO] password 2019-07-29 16:54:23 [(*FabricClient).CreateChannel] : create channel failed: SendEnvelope failed: calling orderer '10.16.32.11:31938' failed: Orderer Client Status Code: (2) CONNECTION_FAILED. Description: dialing connection timed out [10.16.32.11:31938]

### ISSUE THREAD

**Issue by Alilice** [jonluo94/baasmanager#3]
前提：centos7 防火墙已关闭，seLinux设为0  

![Feige图片20190729171740](https://user-images.githubusercontent.com/32505452/62036695-dc885600-b224-11e9-8f0a-102755aab91f.jpg)

![微信图片_20190729172144](https://user-images.githubusercontent.com/32505452/62036927-620c0600-b225-11e9-9543-220c0461e27a.png)
点击添加之后，fabric-engine服务打印出如下错误：
![20c18e2d19f10571d586b8b4e4d7e19](https://user-images.githubusercontent.com/32505452/62037042-997ab280-b225-11e9-904d-531ce33a4a07.png)
查看k8s-dashboard里容器组错误如下：
<img width="1439" alt="505ef997a7d2affe997aaa1b1371e0e" src="https://user-images.githubusercontent.com/32505452/62037542-8d432500-b226-11e9-88fb-aaad0ac9e034.png">

上面说的连接端口号为31938的超时，发现31938是proxy在监听
![f7cb6281d3d1af18c2e20a9dad2294c](https://user-images.githubusercontent.com/32505452/62037696-e317cd00-b226-11e9-864c-bc99dd243414.png)

telnet试了一下，连接不通
![aa73a917bb86172de0c4e9a16854b0f](https://user-images.githubusercontent.com/32505452/62037776-05a9e600-b227-11e9-990e-9ad6d734d8f1.png)

不知道是什么原因，大神帮忙看一下

**Comment by jonluo94** [comment]
看看nfs的配置问题

**Comment by jonluo94** [comment]
nfs pv 可能没有挂载到容器里,容器起不来

**Comment by darrenli6** [comment]
可以留下联系方式吗？
